# Generated by Django 4.2.3 on 2024-07-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_alter_candidate_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election'),
        ),
    ]
